version: '2'

services:
  apache:
    image: porchn/apache-mongo-php
    container_name: apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache2/conf:/etc/apache2/sites-enabled
      - ./apache2/www:/var/www
      - ./apache2/logs:/var/log/apache2
    restart: always
    links: 
      - postfix:postfix

  postfix:
    image: catatnight/postfix
    container_name: postfix
    ports:
      - "25:25"
    environment:
      - maildomain=mail.abc.com
      - smtp_user=abc:123
    volumes:
      - ./postfix/domainkeys:/etc/opendkim/domainkeys
      - ./postfix/logs:/var/log/postfix
      - ./postfix/tls:/etc/postfix/certs
    restart: always
